heat_template_version: 2013-05-23
parameters:
  network:
    type: string
resources:
  cirros_image:
    properties:
      container_format: ami
      disk_format: ami
      location: http://download.cirros-cloud.net/0.3.3/cirros-0.3.3-x86_64-disk.img
      name: cirros-0.3.3-x86_64
    type: OS::Glance::Image
  vm:
    properties:
      flavor: m1.tiny
      image:
        get_resource: cirros_image
      networks:
      - network:
          get_param: network
    type: OS::Nova::Server
